CREATE TABLE public.account (
  id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  password text NOT NULL
);

-- Existing item table remains unchanged
CREATE TABLE public.item (
  id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  text text NOT NULL,
  name text NOT NULL
);
