CREATE TABLE account (
  id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text UNIQUE NOT NULL,
  password text NOT NULL
);

CREATE TABLE profile (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id bigint UNIQUE NOT NULL REFERENCES account(id) ON DELETE CASCADE,
  name       text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
